### ISSUE TITLE
Error when serializing prop types on component

### ISSUE THREAD

**Issue by nddery** [skyrpex/vue-jsx-hot-loader#10]
The serializing occurring in `api.sj` fails when you've declared props with a type of `Object` or `Array`, or any native function basically..

> Uncaught TypeError: Serializing native function: Number

**Comment by skyrpex** [comment]
Oh, I expected the serializing library to work with that. Will try to
reproduce it tomorrow morning. Thanks

**Comment by nddery** [comment]
Adding `props` to the "do not serialize" array in https://github.com/skyrpex/vue-jsx-hot-loader/blob/master/src/api.js#L39 fixes the issue, but I'm wondering if there's maybe a better way, like hashing the whole file or something ?

**Comment by nddery** [comment]
If going the `omit` way, we may also want to omit `staticRenderFns`, as vue-hot-reload-api seems to [hot reload it](https://github.com/vuejs/vue-hot-reload-api/blob/master/index.js#L110-L111) too.

**Comment by skyrpex** [comment]
> Adding props to the "do not serialize" array in https://github.com/skyrpex/vue-jsx-hot-loader/blob/master/src/api.js#L39 fixes the issue, but I'm wondering if there's maybe a better way, like hashing the whole file or something ?

My initial idea is to transform those un-serializable methods (native code) to simple strings (because we don't care what they are; we just want to know when they have changed from the last save).

Related code to the error: https://github.com/yahoo/serialize-javascript/blob/master/index.js#L101-L106

> If going the omit way, we may also want to omit staticRenderFns, as vue-hot-reload-api seems to hot reload it too. (note that I'm not sure what exactly are staticRenderFns)

Will take a look. Have never used it before.

**Comment by skyrpex** [comment]
I've addressed the error in https://github.com/skyrpex/vue-jsx-hot-loader/releases/tag/v1.1.3.

**Comment by nddery** [comment]
Nice! Thanks!

**Comment by nddery** [comment]
I dig a little bit more into this and was wondering why you were serializing the component in the first place ? Seems like setting `serialized` (which would now be a bad name) to `_.omit(component, ['render'])` and saving that to the cache also works. That's what vueif [seems to do](https://github.com/vuejs/vueify/blob/master/lib/compiler.js#L96).

**Comment by skyrpex** [comment]
The Vue reload API has two methods: `api.rerender` (which updates the view and keeps the state) and `api.reload` (which updates the view but resets the state).

When a component source code is changed, we need to be able to differentiate if only the render function has changed. In that case, we can safely use the `api.rerender` instead of `api.reload`.

In order to do so, I serialize the component object (excluding the render function). Each time something from a component changes (ie, the user modifies it and hits Ctrl+S), we check if the serialized component is different from before. If the serialized version has changed, the need to call `api.reload` (because either the data, props, mixins, etc... may have changed); if not, it means that only the render function has changed (so we'll call `api.rerender`).

Vue components (those whose filename end with .vue) can check if the script or the view has changed trivially (just comparing strings).

Not sure if that answers your questions 😆.
